impresario-prod-dev/account_settings/urls.py
from django.urls import path
from . import views

urlpatterns=[
    # path('',views.menu,name="menu"),
    # path('change_password',views.change_password,name="change_password"),
]

impresario-prod-dev/impresario/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',views.index),
    path('userauth/',include('userauth.urls')),
    path('account_settings/',include('account_settings.urls')),
    path('scheduling/',include('scheduling.urls')),
    path('userprofile/',include('userprofile.urls')),
]

impresario-prod-dev/userauth/urls.py
from django.urls import path
from . import views
app_name = 'userauth'

urlpatterns = [
    # path('',views.index,name="index"),
    path('register/',views.register_user,name="register"),
    path('login/',views.login_user,name="login"),
    path('logout/',views.logout_user,name="logout"),
    path('',views.home,name="home"),
    path('menu/',views.menu,name="menu"),
    path('change_password/',views.change_password,name="change_password"),
]

impresario-prod-dev/account_settings/models.py
from django.db import models

# Create your models here.

impresario-prod-dev/userauth/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    first_name=models.CharField(max_length=200,default='')
    last_name=models.CharField(max_length=200,default='')
    gender_choice=((u'M',u'Male'),(u'F',u'Female'),(u'O',u'OTHER'))
    phone_number=models.CharField(max_length=12,default='')
    gender=models.CharField(max_length=2,choices=gender_choice,default='O')
    def __str__(self):
        return self.first_name + " "+self.last_name



class Account(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.user.username

    

impresario-prod-dev/account_settings/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User,auth
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages

# Create your views here.
def menu(request):
    return render(request,'account_settings.html')

def change_password(request):
    if request.method=='POST':
        cur_pwd=request.POST['cur_password']
        pwd=request.POST['password']
        pwd2=request.POST['password2']
        username=request.user.get_username()
        user = User.objects.get(username__exact=username)
        check =auth.authenticate(request, username=username, password=cur_pwd)
        
        if check is None:
            messages.info(request,'Current Password is not correct!!!')
            return redirect('change_password')
        if(pwd==pwd2):            
            user.set_password(pwd)
            user.save()
            update_session_auth_hash(request, user)
            messages.info(request,'Password changed successfully!!!')
            return redirect('change_password')
        else:
            messages.info(request,'New Passwords do not match!!!')
            return redirect('change_password')
    else:
        return render(request,'change_password.html')

impresario-prod-dev/userauth/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User,auth
from django.contrib.auth import authenticate,login,logout, update_session_auth_hash
from .models import Profile, Account 
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request,'index.html',{})
    
def register_user(request):
    if request.method == 'POST':
        try:
            prevuser = User.objects.get(username=request.POST['username'])
            return render(request,'register.html',{'warning':"User already exists!!"})
        except User.DoesNotExist:
            if request.POST['password']==request.POST['password2']:
                user=User.objects.create_user(request.POST['username'],request.POST['email'].lower(),request.POST['password'])
                # user.last_name=request.POST['lname']
                # user.first_name=request.POST['fname']
                user.save()
                profile = Profile(first_name=request.POST['fname'],last_name=request.POST['lname'],phone_number=request.POST['phone'],gender=request.POST['gender'] )
                profile.save()
                account = Account(profile=profile,user=user)                 
                account.save()
                return redirect('/userauth/login')

                
            else:
                return render(request,'register.html',{'warning':"Passwords do not match!!"})
    return render(request,'register.html',{})

def login_user(request):
    if request.method=='POST':
        user = authenticate(request,username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request,user)
            return redirect('/userauth')
        else:
            return render(request,'login.html',{'warning':"Incorrect username or password"})

    return render(request,'login.html',{})
    
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
      
    return redirect('/userauth')


def home(request):
    if request.user.is_authenticated:
        account = Account.objects.get(user=request.user.id)
        print(account) 
        return render(request,'home.html',{'account':account})
    else:
        return render(request,'index.html')

def menu(request):
    if request.user.is_authenticated:
        return render(request,'account_settings.html',{'user':request.user})
    else:
        return redirect('/userauth/login')
def change_password(request):
    if not request.user.is_authenticated:
         return redirect('/userauth/login')
    if request.method=='POST':
        cur_pwd=request.POST['cur_password']
        pwd=request.POST['password']
        pwd2=request.POST['password2']
        username=request.user.get_username()
        user = User.objects.get(username__exact=username)
        check =auth.authenticate(request, username=username, password=cur_pwd)
        
        if check is None:
            messages.info(request,'Current Password is not correct!!!')
            return redirect('userauth:change_password')
        if(pwd==pwd2):            
            user.set_password(pwd)
            user.save()
            update_session_auth_hash(request, user)
            messages.info(request,'Password changed successfully!!!')
            return redirect('userauth:change_password')
        else:
            messages.info(request,'New Passwords do not match!!!')
            return redirect('userauth:change_password')
    else:
        return render(request,'settings.html')

impresario-prod-dev/userauth/templates/account_settings.html
{% extends 'adminbase.html' %}
{% block title %}Account Setting{% endblock %}
{% block body %}
<div class="container fadeIn" style="background-color:#f2d9d91c" > 
<h3>MENU</h3>
<li><a href="{% url 'userauth:change_password' %}">Change Password</a></li>
<br>
<a class="btn btn-danger mx-20 my-10" href="{% url 'userauth:logout' %}">LOGOUT</a>
</div>
{% endblock %}

impresario-prod-dev/userauth/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Impresario</title>
    <meta name="description" content="IE NITK" />
    <meta
      name="keywords"
      content="IE NITK, exclusive technical club, ie nitk, ie-nitk, NITK, Institution of Engineers, NITK Chapter, Institution of Engineers"
    />

    <meta property="og:title" content="IE NITK" />
    <meta
      property="og:description"
      content="IE NITK aims to enhance the technical expertise of its members and the student community, while acknowledging the importance of fine arts and social work."
    />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://ie.nitk.ac.in" />
    <meta property="og:image" content="{% static 'img/favicon.ico' %}" />

    <link rel="stylesheet" type="" href="" />
    <link rel="icon" href="{% static 'img/favicon.ico' %}" title="IE NITK" />
    <link
      href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,700|Open+Sans"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles-merged.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style-dark.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
      crossorigin="anonymous"
    />
    <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
    crossorigin="anonymous"
    />

    <!-- <script src="{% static 'js/scripts.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script> -->
    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.min.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
    <script
      language="JavaScript"
      type="text/javascript"
      src="https://code.jquery.com/jquery-3.3.1.min.js"
    ></script>
  </head>
  <body>
    <div class="probootstrap-search" id="probootstrap-search">
      <a href="#" class="probootstrap-close js-probootstrap-close">
        <i class="icon-cross"></i>
      </a>
      <form action="#">
        <input
          type="search"
          name="s"
          id="search"
          placeholder="Search a keyword and hit enter..."
        />
      </form>
    </div>

    <div class="probootstrap-page-wrapper">
      <!-- Fixed navbar -->

      <div class="probootstrap-header-top">
        <div class="container">
          <div class="row">
            <div
              class="col-lg-9 col-md-9 col-sm-9 probootstrap-top-quick-contact-info"
            >
              <span>
                <i class="icon-location2"></i> National Institute of Technology
                Karnataka, Surathkal
              </span>
              <!-- <span><i class="icon-phone2"></i>+1-123-456-7890</span> -->
              <span><i class="icon-mail"></i>ie@nitk.edu.in</span>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 probootstrap-top-social">
              <ul>
                <li>
                  <a href="https://github.com/IE-NITK" target="_blank">
                    <i class="icon-github2"></i>
                  </a>
                </li>
                <li>
                  <a href="https://www.facebook.com/ienitk/" target="_blank">
                    <i class="icon-facebook2"></i>
                  </a>
                </li>
                <li>
                  <a href="https://www.instagram.com/ienitk/" target="_blank">
                    <i class="icon-instagram2"></i>
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.linkedin.com/company/ienitk/"
                    target="_blank"
                  >
                    <i class="icon-linkedin"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/ienitk">
                    <i class="icon-twitter"></i>
                  </a>
                </li>
                <li>
                  <a href="/blog"> <i class="icon-blog"></i> </a>
                </li>
                
                {% if user.is_authenticated %}
                <li>
                  <a href="{% url 'userauth:logout' %}">
                    <i class="fas fa-sign-out-alt"></i>
                  </a>
                </li>
                {% else %}
                <li>
                  <a href="{% url 'userauth:login' %}">
                    <i class="icon-login"></i>
                  </a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>

      <nav class="navbar navbar-default probootstrap-navbar">
        <div class="container">
          <div class="navbar-header">
            <div class="btn-more js-btn-more visible-xs">
              <a href="#"> <i class="icon-dots-three-vertical"></i> </a>
            </div>
            <button
              type="button"
              class="navbar-toggle collapsed"
              data-toggle="collapse"
              data-target="#navbar-collapse"
              aria-expanded="false"
              aria-controls="navbar"
            >
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ie.nitk.ac.in" title="IE NITK"
              >IE NITK</a
            >
          </div>
          <div id="navbar-collapse" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="{% block index %}{% endblock %}">
                <a href="{% url 'userauth:home' %}">Home</a>
              </li>
              {% comment %} <li class="{% block sig %}{% endblock %}">
                <a href="{% url 'userprofile:new_team' %}">Create team</a>
              </li>
              <li class="{% block events %}{% endblock %}">
                <a href="{% url 'userprofile:team_request' %}">Team requests</a>
              </li>
              <li class="{% block teams %}{% endblock %}">
                <a href="{% url 'userprofile:view_calendar' %}">Calendar</a>
              </li> {% endcomment %}

              {% if user.is_authenticated %}
              <li><a href="{% url 'userauth:logout' %}">Logout</a></li>
              {% else %}
              <li><a href="{% url 'userauth:login' %}">Login</a></li>
              <li>
                <a href="{% url 'userauth:register' %}"><b>Register</b></a>
              </li>
              {% endif %}
            
            </ul>    
          </div>
        </div>
      </nav>
      <main>{% block content %} {% endblock %}</main>

      <footer class="probootstrap-footer probootstrap-bg">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="probootstrap-footer-widget">
                <h3>About IE NITK</h3>
                <p>
                  Institution of Engineers, NITK Chapter, is one of the six
                  exclusive clubs in NITK. We are divided by three core Special
                  Interest Groups (SIGs) - Code, Gadget and Garage; but united
                  by five auxiliary SIGs - Vriddhi, our social initiative,
                  Script, our literary SIG, Robotics, Business and Tectonic, our
                  newest SIG for Civil and Architecture.
                </p>
                <h3>Social</h3>
                <ul class="probootstrap-footer-social">
                  <li>
                    <a href="https://facebook.com/ienitk" target="_blank">
                      <i class="icon-facebook"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://github.com/IE-NITK" target="_blank">
                      <i class="icon-github"></i>
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://www.linkedin.com/company/ienitk/"
                      target="_blank"
                    >
                      <i class="icon-linkedin"></i>
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://www.instagram.com/ienitk/?hl=en"
                      target="_blank"
                    >
                      <i class="icon-instagram"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://twitter.com/ienitk">
                      <i class="icon-twitter"> </i>
                    </a>
                  </li>
                  <li>
                    <a href="/blog/"> <i class="icon-blog"></i> </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-3 col-md-push-1">
              <div class="probootstrap-footer-widget">
                <h3>Links</h3>
                {% comment %} <!-- <ul>
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'events:events' %}">Events</a></li>
                  <li><a href="{% url 'sig:sig' %}">SIGs</a></li>
                  <li><a href="/blog">Blog</a></li>
                  <li><a href="{% url 'teams:teams' %}">Team</a></li>
                  <li><a href="{% url 'flappy' %}">Bored?</a></li>
                </ul> --> {% endcomment %}
              </div>
            </div>
            <div class="col-md-4">
              <div class="probootstrap-footer-widget">
                <h3>Contact Info</h3>
                <ul class="probootstrap-contact-info">
                  <li>
                    <i class="icon-location2"></i>
                    <span
                      >National Institute of Technology Karnataka,
                      Surathkal</span
                    >
                  </li>
                  <li><i class="icon-mail"></i><span>ie@nitk.edu.in</span></li>
                  <!-- <li><i class="icon-phone2"></i><span>+123 456 7890</span></li> -->
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="probootstrap-copyright">
          <div class="container">
            <div class="row">
              <div class="col-md-8 text-left">
                <p>
                  &copy;
                  <script>
                    document.write(new Date().getFullYear());
                  </script>
                  Built with <i class="icon icon-heart"></i> at IE NITK
                </p>
              </div>
              <div class="col-md-4 probootstrap-back-to-top">
                <p>
                  <a href="#" class="js-backtotop"
                    >Back to top <i class="icon-arrow-long-up"></i
                  ></a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=UA-126629212-1"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
        dataLayer.push(arguments);
      }

      gtag("js", new Date());

      gtag("config", "UA-126629212-1");
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

impresario-prod-dev/userauth/templates/change_password.html
{%extends 'adminbase.html' %}
{% load static%}
{% block title %} Change Password {% endblock %}
{% block body %}

<form action="{% url 'userauth:change_password' %}" method='post'>
    {%csrf_token%}
    Current Password:<input type="password" name="cur_password"><br>
    New Password:<input type="password" name="password"><br>
    confirm Password:<input type="password" name="password2"><br>
    <input type="submit">
</form>
<div>
    {%for message in messages%}
    <h3>{{message}}</h3>
    {%endfor%}
</div>
<br>
<a class="btn btn-primary mx-10 my-10" href="{% url 'userauth:home' %}">Home</a>
<a class="btn btn-danger mx-20 my-10" href="{% url 'userauth:logout'%}">LOGOUT</a>
{%endblock%}

impresario-prod-dev/userauth/templates/login.html
{% extends 'adminbase.html' %}
<!DOCTYPE html>
{% load static %}
{% block title %}Login {% endblock %}

{% block active %} 
<li><a href="{% url 'userauth:home' %}">HOME</a></li>
    {% if user.is_authenticated %}
      <li class="active"><a href="/scheduling">EXISTING TEAMS</a></li>  
      <li><a href="{% url 'new_team' %}">CREATE TEAM</a></li>
      {% comment %} <li><a href="{% url 'team_request' par_id %}">TEAM REQUESTS</a></li> {% endcomment %}
      <li><a href="{% url 'view_calendar' %}">CALENDAR</a></li>
      {% else %}
     
      <li><a href="/userauth/login">Login</a></li>  
      <li><a href="/userauth/register">Register</a></li>
      {% comment %} <li><a href="{% url 'team_request' par_id %}">TEAM REQUESTS</a></li> {% endcomment %}
     {% endif%}
{% endblock %}

{% block body %}

<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <!-- <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div> -->
 {% comment %} {% if error_message %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error!</strong>           {{ error_message }}        

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
             <span aria-hidden="true">&times;</span>
           </button>
          </div>
          
        {% endif %}     {% endcomment %}

    <!-- Login Form -->
    <form action="{% url 'userauth:login'%}" method="POST">
    {% csrf_token %}
      <input required name="username"  id="login" type="text" class="fadeIn second"  placeholder="Username">
      <input required type="password" name= "password" id="password"  class="fadeIn third"  placeholder="password">
      <input type="submit" class="fadeIn fourth" value="Log In">
    
    </form>
  <p class="text-center">
    New to impresario?
    <a class="font-weight-bold" href="{% url 'userauth:register' %}">
    Register
    </a>
  </p>
    <!-- Remind Password -->
    {% comment %} <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password? </a>
    </div> {% endcomment %}

  </div>
</div>
{% endblock %}

impresario-prod-dev/userauth/templates/register.html
{% extends 'adminbase.html' %}

{% comment %} <html lang="en">
  <head>
  <title>Home:Impresario</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>

  <body class="text-center">
        <br>
        <br>
        <div class="container" style="border:2px solid black;box-shadow:5px 5px 5px black"> 
       {% if error_message %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error!</strong>           {{ error_message }}        

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
           </button>
          </div>
          
        {% endif %}    
  

        <h1 class="font-weight-bold text-center">Register</h1>
        <h3>
        Fill all the details to continue..
        </h3>
        <form action="{% url 'userauth:register' %}" method="POST">
        {% csrf_token %}
           <div class="form-group">
           
            <label for="username">Username:</label>
            <input required type="text" name="username" class="form-control" id="username" aria-describedby="emailHelp">
    
          </div>
           <div class="form-group">

            <label for="fname">First name:</label>
            <input required type="text" name="fname" class="form-control" id="fname" aria-describedby="emailHelp">
    
          </div>
           <div class="form-group">

            <label for="lname">Last name:</label>
            <input required type="text" name="lname" class="form-control" id="lname" aria-describedby="emailHelp">
    
          </div>
          <div class="form-group">
        <label for="email">Email address</label>
        <input required type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp">
        </div>
          <div class="form-group">
          <label for="phone">Phone no.</label>
          <input required type="text" name="phone" class="form-control" id="phone" aria-describedby="emailHelp">
        </div>
          <div class="form-group">
          <div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" name="gender" id="inlineRadio1" value="M">
  <label class="form-check-label" for="inlineRadio1">Male</label>
</div>
    <div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" name="gender" id="inlineRadio2" value="F">
  <label class="form-check-label" for="inlineRadio2">Female</label>
    </div>
    <div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" name="gender" id="inlineRadio3" value="O">
  <label class="form-check-label" for="inlineRadio3">Other</label>
    </div>
        </div>
         
  <div class="form-group">
    <label for="password1">Password</label>
    <input required type="password" name="password" class="form-control" id="password1">
  </div>
  
  <div class="form-group">
    <label for="password2">Confirm Password</label>
    <input required name="password2" type="password" class="form-control" id="password2">
  </div>
  <div class="d-flex flex-row justify-content-around my-20">
        
       
  <button type="submit" class="btn btn-primary">Register</button>
  <a href="{% url 'index' %}" class="btn btn-danger">Cancel</a>
        

        </div>
  </form>
 {% csrf_token %}
 <p class="text-center">
  Already have an account?
  <a class="font-weight-bold" href="{% url 'userauth:login' %}">
  Login
  </a>
  </p>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

<br>
<br>
<br> {% endcomment %}


<!DOCTYPE html>
{% load static %}
{% block title %}Register {% endblock %}

{% block active %} 
 <li><a href="{% url 'userauth:home' %}">HOME</a></li>
    {% if user.is_authenticated %}
      <li class="active"><a href="/scheduling">EXISTING TEAMS</a></li>  
      <li><a href="{% url 'new_team' %}">CREATE TEAM</a></li>
      {% comment %} <li><a href="{% url 'team_request' par_id %}">TEAM REQUESTS</a></li> {% endcomment %}
      <li><a href="{% url 'view_calendar' %}">CALENDAR</a></li>
      {% else %}
     
      <li><a href="/userauth/login">Login</a></li>  
      <li><a href="/userauth/register">Register</a></li>
      {% comment %} <li><a href="{% url 'team_request' par_id %}">TEAM REQUESTS</a></li> {% endcomment %}
     {% endif%}
{% endblock %}

{% block body %}
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <!-- <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div> -->

    <!-- Login Form -->
    {% comment %} {% if error_message %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error!</strong>           {{ error_message }}        

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
           </button>
          </div>
          
        {% endif %}     {% endcomment %}
    
    <form action="{% url 'userauth:register' %}" method="POST">
    {% csrf_token %}
      <input required type="text" id="name" class="fadeIn second" name="username" placeholder="username">
      <input required type="text" id="name" class="fadeIn third" name="fname" placeholder="First Name">
      <input required type="text" id="name" class="fadeIn third" name="lname" placeholder="Last Name">
      <input required type="text" id="email-id" class="fadeIn third" name="email" placeholder="email id">
      <input required type="password" id="enter password" class="fadeIn fourth" name="password" placeholder="enter password">
      <input required type="password" id="confirm password" class="fadeIn fifth" name="password2" placeholder="confirm password">
		 <input type="text" id="phone number" class="fadeIn sixth" name="phone" placeholder="phone number">
    <br><br>
    <tr>
        <td>
          <p>Gender: </p><div class="form-check form-check-inline">
            <input type="radio" class="form-check-input" id="materialInline1" name="gender" value='M'>
            <label class="form-check-label" for="materialInline1">Male</label>
          </div>
        </td>
    
        <!-- Material inline 2 -->
        <td>
        <div class="form-check form-check-inline">
        <input type="radio" class="form-check-input" id="materialInline2"  name="gender" value='F'>
        <label class="form-check-label" for="materialInline2">Female</label>
        </div> </td>
    
        <!-- Material inline 3 -->
        <td>
        <div class="form-check form-check-inline">
        <input type="radio" class="form-check-input" id="materialInline3"  name="gender" value='O'>
        <label class="form-check-label" for="materialInline3">Other</label>
        </div></td><br>
    </tr>
     
      <input type="submit" class="fadeIn seventh" value="Sign up">
    </form>

    <!-- Remind Password -->
    <div id="formFooter">
      <a class="underlineHover" href="{% url 'userauth:login' %}" >Already registered? Log in here.</a>
    </div>

  </div>
</div>
{% endblock %}